name: DeathBan
description: ${project.description}
author: ItsLeMax
version: ${project.version}
website: ${project.url}

main: de.max.deathban.init.DeathBan
api-version: 1.20
commands:
  toggledeathban:
    description: Aktiviert oder deaktiviert, ob Spieler nach dem Tod temporär gesperrt werden
    usage: /toggledeathban
    aliases:
      - toggleban
      - toggledeath