name: DeathBan
description: ${project.description}
author: ItsLeMax
version: ${project.version}
website: ${project.url}

depend: [ ILMLib ]
main: de.max.deathban.init.DeathBan
api-version: 1.20
commands:
  toggledeathban:
    description: Toggles the plugin functionality with a hint to everyone
    usage: /toggledeathban
    aliases:
      - toggleban
      - toggledeath